language: julia
os:
    - osx
    - linux
julia:
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("IterativeSolvers"); Pkg.test("IterativeSolvers"; coverage=true)'
    - julia -e 'cd(Pkg.dir("IterativeSolvers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coverage.process_folder()); Codecov.submit(Coverage.process_folder())'
