site_name: IterativeSolvers.jl

site_description: Iterative numerical linear algebra in Julia

repo_url: https://github.com/JuliaLang/IterativeSolvers.jl

pages:
- [index.md]
- [LICENSE.md, About, License]

theme: journal

markdown_extensions: [codehilite]
